#!/bin/bash
set -euo pipefail

# note need to use greadlink for MacOS (from gnu core utils), readlink for Linux
SCRIPT_DIR="$(dirname "$(greadlink -f "$0")")"

TARGET=$(ls "$SCRIPT_DIR"/problems |fzf)
echo "Running practice for $TARGET"

source "$SCRIPT_DIR"/venv/bin/activate

SOURCE_NAME="run.py"
TEST_NAME="test_run.py"
cp "$SCRIPT_DIR"/problems/${TARGET}/$SOURCE_NAME $SOURCE_NAME
cp "$SCRIPT_DIR"/problems/${TARGET}/$TEST_NAME $TEST_NAME
nvim -O $SOURCE_NAME $TEST_NAME
